# Generated by Django 2.2.18 on 2021-03-07 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(max_length=200)),
                ('followers', models.ManyToManyField(to='SNS.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=170)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='SNS.CustomUser')),
                ('replyTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SNS.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS.Post')),
                ('repostedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='SNS.Post'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reposts',
            field=models.ManyToManyField(through='SNS.Repost', to='SNS.Post'),
        ),
    ]
