# Generated by Django 2.2.17 on 2021-02-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0006_auto_20210212_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repliedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SNS.Post'),
            preserve_default=False,
        ),
    ]
