# Generated by Django 2.2.17 on 2021-02-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0008_auto_20210215_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replyTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SNS.Post'),
        ),
    ]
